# Generated by Django 5.2.15 on 2026-07-07 11:10
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='follow',
                    table='blog_follow',
                ),
            ],
            database_operations=[],
        ),
    ]