# Generated by Django 5.2.15 on 2026-07-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only')], default='public', max_length=10),
        ),
    ]
