# Generated by Django 5.2.15 on 2026-07-07 11:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_follow'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Follow',
                ),
            ],
            database_operations=[],
        ),
    ]